const PDFDocument = require("pdfkit");

const TEAL = "#0F6E56";
const DARK = "#1F2937";
const GRAY = "#6B7280";

const SEVERITY_LABEL = { mild: "MILD", moderate: "MODERATE", severe: "SEVERE" };
const SEVERITY_COLOR = { mild: "#B7791F", moderate: "#C05621", severe: "#C53030" };

/**
 * Generates a doctor-visit-ready PDF: current medication list + all active
 * flagged interactions (with cached AI explanations / doctor questions).
 * Returns a Buffer.
 */
function generateReportPDF({ patient, medications, flags }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.fillColor(TEAL).fontSize(22).font("Helvetica-Bold").text("MedGuard AI", { continued: false });
    doc.fillColor(DARK).fontSize(14).font("Helvetica").text("Doctor Visit Report");
    doc.fillColor(GRAY).fontSize(10).text(`Generated: ${new Date().toLocaleString()}`);
    doc.moveDown(0.3);
    doc.fillColor(GRAY).fontSize(10).text(`Patient: ${patient.name}${patient.age ? `  |  Age: ${patient.age}` : ""}`);
    doc.moveDown(1);
    line(doc);
    doc.moveDown(0.8);

    // Medications
    doc.fillColor(TEAL).fontSize(15).font("Helvetica-Bold").text("Current Medications");
    doc.moveDown(0.4);

    if (medications.length === 0) {
      doc.fillColor(GRAY).fontSize(11).font("Helvetica").text("No active medications on file.");
    } else {
      medications.forEach((m, i) => {
        doc.fillColor(DARK).fontSize(12).font("Helvetica-Bold").text(`${i + 1}. ${m.name}`);
        doc.fillColor(GRAY).fontSize(10).font("Helvetica").text(
          `Dosage: ${m.dosage}  |  Frequency: ${m.frequency}${m.prescribing_doctor ? `  |  Prescribed by: ${m.prescribing_doctor}` : ""}`
        );
        doc.moveDown(0.4);
      });
    }

    doc.moveDown(0.6);
    line(doc);
    doc.moveDown(0.8);

    // Flagged interactions
    doc.fillColor(TEAL).fontSize(15).font("Helvetica-Bold").text("Active Flagged Interactions");
    doc.moveDown(0.4);

    if (flags.length === 0) {
      doc.fillColor(GRAY).fontSize(11).font("Helvetica").text("No active interactions flagged at this time.");
    } else {
      flags.forEach((f, i) => {
        const sevColor = SEVERITY_COLOR[f.severity] || GRAY;
        doc.fillColor(DARK).fontSize(12).font("Helvetica-Bold").text(
          `${i + 1}. ${f.medication_a_id?.name || "Medication A"}  +  ${f.medication_b_id?.name || "Medication B"}`,
          { continued: true }
        );
        doc.fillColor(sevColor).font("Helvetica-Bold").text(`   [${SEVERITY_LABEL[f.severity] || f.severity}]`);

        const refDesc = f.interaction_reference_id?.description;
        if (refDesc) {
          doc.fillColor(DARK).fontSize(10).font("Helvetica").text(refDesc);
        }

        if (f.ai_explanation) {
          doc.moveDown(0.2);
          doc.fillColor(GRAY).fontSize(9).font("Helvetica-Oblique").text(
            "AI-generated \u2014 not medical advice", { continued: false }
          );
          doc.fillColor(DARK).fontSize(10).font("Helvetica").text(f.ai_explanation);
        }

        if (f.ai_doctor_questions && f.ai_doctor_questions.length) {
          doc.moveDown(0.2);
          doc.fillColor(DARK).fontSize(10).font("Helvetica-Bold").text("Questions to ask your doctor:");
          f.ai_doctor_questions.forEach((q) => {
            doc.fillColor(DARK).fontSize(10).font("Helvetica").text(`\u2022 ${q}`);
          });
        }

        doc.moveDown(0.6);
      });
    }

    doc.moveDown(1);
    line(doc);
    doc.moveDown(0.5);
    doc.fillColor(GRAY).fontSize(8).font("Helvetica-Oblique").text(
      "This report is generated by MedGuard AI for informational purposes only. It does not " +
      "constitute medical advice, diagnosis, or treatment. Always consult a licensed healthcare " +
      "provider about your medications.",
      { align: "left" }
    );

    doc.end();
  });
}

function line(doc) {
  doc.strokeColor("#E5E7EB").lineWidth(1)
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .stroke();
}

module.exports = { generateReportPDF };
